# Generated by Django 5.2.11 on 2026-02-05 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=50)),
                ('flowrate', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('temperature', models.IntegerField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='core.fileupload')),
            ],
        ),
    ]
