# Generated by Django 5.2.11 on 2026-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdata',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
    ]
